// <auto-generated />
namespace BL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class LTsCrmMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LTsCrmMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202103071835032_[LTsCrmMigration]"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
